config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  get 'pages/terms'

  get 'pages/rules'

  get 'pages/privacy'

  devise_for :admins
  devise_for :users
  resources :posts
  resources :users 

  root 'posts#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :trackable, :timeoutable, :lockable 

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	CONSOLE_LIST = ["PS4", "PS3", "XBOX", "WII"]

	validates_presence_of :name, :console, :category, :image
	validates :console, :inclusion=> { :in => CONSOLE_LIST }

	default_scope -> { order('created_at DESC') }
	scope :by_console, -> (console){where(console: console)}

	has_attached_file :post_img, styles: { post_index: "250x350>", post_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :post_img, content_type: /\Aimage\/.*\Z/

  def can_edit?(current_user,post) 
  	if (current_user && current_user.id == post.user_id) || current_user.try(:admin?)
  		return true
  	end
  end
  
  def self.search(search)
	  where("name LIKE ?", "%#{search}%") 
	  where("console LIKE ?", "%#{search}%")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :resource, :resource_name, :devise_mapping
  before_action :configure_permitted_parameters, if: :devise_controller?

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  protected

  # def configure_premitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:first_name, :last_name, :username, :birthday, :email, :password, :remember_me)}
  #   devise_parameter_sanitizer.for(:sign_in) {|u| u.permit(:email, :password, :remember_me)}
  #   devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:first_name, :last_name, :username, :birthday, :about, :email, :password, :remember_me)}
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |user_params|
      user_params.permit(:first_name, :last_name, :username, :birthday, :email, :password, :remember_me)
    end

    devise_parameter_sanitizer.for(:account_update) do |user_params|
      user_params.permit(:first_name, :last_name, :username, :birthday, :about, :email, :password, :current_password, :remember_me)
    end
  end

  
end
 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def rules
  end

  def privacy
  end

  def contact
  end

  def blank
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action  :user_logged_in?, only: [:new]

  # GET /posts
  # GET /posts.json
  def index
    if params[:console]
    @posts = Post.by_console(params[:console])
  else
    @posts = Post.all
  end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  def edit3
  end
  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        flash[:notice] = 'Post was successfully created.'
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        flash[:notice] = 'Post was successfully updated.'
        format.html { redirect_to @post }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update2
  end
  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    flash[:notice] = 'Post was successfully destroyed.'
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:console, :name, :category, :prefered, :image, :user_id, :note, :swaped, :post_img)
    end

    def user_logged_in?
      return true if user_signed_in?
      redirect_to new_user_session_path, data: {confirm: "You sure" }
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def selected_platform
		 params[:console].blank? ? "Selected platform" : params[:console]
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_flash_messeages.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-top alert-info alert-dismissible fade in flash-padding" role="alert">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <%= flash[:notice] %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% unless defined?(object).nil? %>
  <% if object.errors.any? && flash[:notice].blank? %>
    <div class="alert alert-top alert-info alert-dismissible fade in flash-padding" role="alert">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
            <ul>
            <% object.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
          </div>         
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/application/_footer.html.erb
<div id="gswap-footer">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<ul class="list-inline text-center footer-content">
					<li>
						Gswap &copy; 2016
					</li>
					<li>
						<a><%= link_to "Terms", pages_terms_path %></a>
					</li>
					<li>
						<a><%= link_to "Privacy", pages_privacy_path%></a>
					</li>
					<li>
						<a><%= link_to "Rules", pages_rules_path%></a>
					</li>										
				</ul>
		</div>
	</div>
</div>

app/views/application/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Gswap", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav"  >
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%=selected_platform%>
            <span class="caret"></span></a>
          <ul class="dropdown-menu" id="console-dropdown">
            <li><%= link_to "PS4", posts_path(:console=>"PS4")%></li>
            <li><%= link_to "PS3", posts_path(:console=>"PS3")%></li>
            <li><%= link_to "XBOX", posts_path(:console=>"XBOX")%></li>
            <li><%= link_to "WII", posts_path(:console=>"WII")%></li>
          </ul>
        </li>
        <li>
          <%= form_tag posts_path, :method => 'get' do %>
            <%= text_field_tag :search, params[:search]%>
            <%= submit_tag "Search"%>
          <% end %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "Create new Post", new_post_path, class: "btn"%></li>
      	<% if current_user %>

	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
	          		<%= image_tag("user_photo_profile.jpg") %>
	          </a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Timeline</a></li>
	            <li><%= link_to "Profile", users_show_path(:id =>current_user.id) %></li>
	            <li><a href="#">Notifications</a></li>
	            <li role="separator" class="divider"></li>
	            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
	          </ul>
	        </li>
	       <% else %>
          <li><a class="btn-social sign-in" style="cursor:pointer;"><i class='icon-mail-alt'></i>  Sign in</a>
          </li>
	       <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<script type="text/javascript">
$(document).on('click', '.sign-in', function(e){
  $(".sign_in").html("<%= j render(partial: 'sign_in') %>");
  $('.sign_in #sign_in-modal').modal('show');
});
</script>

app/views/application/_sign_in.html.erb
  <div class="modal fade" id="sign_in-modal">
    <div class="modal-dialog modal-sm" role ="document">
      <div class="modal-content">
        <div class="modal-body text-center">
          <div class="modal-body" id="modal-container">
            <h3 class="modal-title">Please Sign in</h3>
              <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
              <div class="form-group">
                  <%= f.email_field :email, :required => true, class: "form-control", :placeholder => "Email address" %>
                </div>
                <div class="form-group">
                  <%= f.password_field :password, :required => true, class: "form-control", :placeholder => "password" %>
                </div>
                <div class="form-group">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me %>
                </div>
              <div class="modal-footer">
              <%= f.submit "Sign in", class: "btn btn-primary center-block" do %>
                <% end %>
            </div>
            Don't have an account?
            <li><a class="btn-social sign-up" style="cursor:pointer;"><i class='icon-mail-alt'></i>  Sign up here</a>
            </li>
        <%end%>
      </div>
    </div>
  </div>

<script type="text/javascript">
$(document).on('click', '.sign-up', function(e){
  $("#modal-container").html("<%= j render(partial: 'sign_up') %>");

});
</script>

app/views/application/_sign_up.html.erb
<h2>Sign up</h2>
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="form-group">
    <%= f.text_field :first_name, :required => true, class: "form-control", :placeholder => "First name" %>
  </div>

  <div class="form-group">
    <%= f.text_field :last_name, :required => true, class: "form-control", :placeholder => "Last name" %>
  </div>

  <div class="form-group">
    <%= f.text_field :username, :required => true, class: "form-control", :placeholder => "User name" %>
  </div>

  <div class="form-group">
    <%= f.date_field :birthday, :required => true, class: "form-control", :placeholder => "Birthday" %>
  </div>

  <div class="form-group">
    <%= f.email_field :email, :required => true, class: "form-control", :placeholder => "Email address" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, :required => true, class: "form-control", :placeholder => "password" %>
  </div>
  <div class="form-group">
    <%= f.password_field :password, :required => true, class: "form-control", :placeholder => "password confirmation" %>
  </div>
  <div class="modal-footer">
    <%= f.submit "Sign up", class: "btn btn-primary center-block" do %>
  <% end %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gswap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'header' %>
  <div class="col-md-3">
  	<h3>Treanding</h3>
      <ul class="nav nav-trending">
      
      </ul>
  	<h3>News</h3>
      <ul class="nav nav-trending">
      
      </ul>      
  </div>
	<div class="col-md-9">
		<div class="row">
      <div class="sign_in"></div>
			<%= yield %>
		</div>
	</div>
	</div>
	<%= render 'footer' %>
</body>
</html>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/rules.html.erb
<h1>Rules Page</h1>
<p>Find me in app/views/pages/rules.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/posts/_form.html.erb
<%= render 'application/flash_messeages', object: @post %>
<%= form_for(@post) do |f| %>
  <div class="field">
    <%= f.label :console %><br>
    <%= f.select(:console, options_for_select(Post::CONSOLE_LIST), :include_blank => "Please choose one" )%>
  </div>
  <div class="field">
    <%= f.file_field :post_img %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :placeholder => "required" %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category, :placeholder => "required" %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image, :placeholder => "required"  %>
  </div>  
  <div class="field">
    <%= f.label :prefered %><br>
    <%= f.text_field :prefered, :placeholder => "Optinal" %>
  </div>
  <div class="field">
    <%= f.label :further_note %><br>
    <%= f.text_field :note, :placeholder => "Optinal" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%=link_to "create new user", new_user_session_path%>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render 'application/flash_messeages' %>
<h1>Listing Posts</h1>
<h3><%= params[:console] %></h3>
<% if @posts.count == 0%>
  <h3>There is no posts currently in this category</h3>
<%end%>

<table>
  <thead>
    <tr>
      <th>Console</th>
      <th>Name</th>
      <th>Category</th>
      <th>Prefered</th>
      <th>Image</th>
      <th>User</th>
      <th>Note</th>
      <th>Swaped</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.console %></td>
        <td><%= post.name %></td>
        <td><%= post.category %></td>
        <td><%= post.prefered %></td>
        <td><%= image_tag post.post_img.url(:post_index) %></td>
        <td><%= post.user_id %></td>
        <td><%= post.note %></td>
        <td><%= post.swaped %></td>
        <td><%= link_to 'Show', post %></td>
        <% if post.can_edit?(current_user,post) %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render 'application/flash_messeages', object: @post %>
<p>
  <strong>Console:</strong>
  <%= @post.console %>
</p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @post.category %>
</p>

<p>
  <strong>Prefered:</strong>
  <%= @post.prefered %>
</p>

<p>
  <strong>Image:</strong>
  <%= @post.image %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Note:</strong>
  <%= @post.note %>
</p>

<p>
  <strong>Swaped:</strong>
  <%= @post.swaped %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/show.html.erb
<h1><%=@user.first_name%></h1>
<%= link_to "Edit profile", edit_user_registration_path%>